services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
        MYSQL_USER: jbank
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: jbankdb
    ports:
      - 3306:3306